name: starter-hello-world-workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo Hello from Starter, ${{ inputs.username }}
