# This workflow will launch the test coverage retrieving for deepsource test coverage project
# A test coverage file should be produce by any plugin you use for your application
# ===== Java Example
# For a java application, we could use for example the Jacoco plugin.
# The test phase of the maven plugin will create for example a test coverage file on target/site/jacoco/jacoco.xml (This path will be use for the coverage_file)

name: Report test coverage to Deepsource

on:
  workflow_call:
    inputs:
      coverage_file:
        required: true
        type: string
      programming_language:
        required: true
        type: string
    secrets:
      deepsource_dsn:
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: deepsourcelabs/test-coverage-action@master
        with:
          key: ${{ inputs.programming_language }}
          coverage-file: ${{ inputs.coverage_file }}
          dsn: ${{ secrets.deepsource_dsn }}

